import {
    expect,
    test,
    describe,
} from "vitest";

import colorBridge from "../lib/main"
import { Culture, Feeling } from "../lib/types";
import { colorAssociations, defaultPalette } from "../lib/constants";
import { darkenHexColor, lightenHexColor } from "../lib/utils";

describe('main', () => {
    test('should return palettes for a culture passed in params', () => {
        expect(colorBridge({ culture: Culture.CHINESE })).toStrictEqual({
            palette: {
                [Feeling.CAUTION]: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]],
                [Feeling.DANGER]: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]],
                [Feeling.ENERGY]: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]],
                [Feeling.ERROR]: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]],
                [Feeling.GROWTH]: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]],
                [Feeling.HAPPINESS]: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]],
                [Feeling.INNOVATION]: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]],
                [Feeling.LUCK]: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]],
                [Feeling.MOURNING]: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]],
                [Feeling.NEUTRALITY]: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]],
                [Feeling.OPTIMISM]: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]],
                [Feeling.SADNESS]: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]],
                [Feeling.STABILITY]: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]],
                [Feeling.SUCCESS]: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]],
                [Feeling.URGENCY]: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]]
            },
            paletteHues: {
                [Feeling.CAUTION]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.CAUTION][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.DANGER]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.DANGER][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.ENERGY]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ENERGY][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.ERROR]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.ERROR][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.GROWTH]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.GROWTH][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.HAPPINESS]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.HAPPINESS][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.INNOVATION]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.INNOVATION][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.LUCK]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.LUCK][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.MOURNING]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.MOURNING][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.NEUTRALITY]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.NEUTRALITY][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.OPTIMISM]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.OPTIMISM][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.SADNESS]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SADNESS][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.STABILITY]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.STABILITY][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.SUCCESS]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.SUCCESS][Culture.CHINESE]], force: 0.8}),
                ],
                [Feeling.URGENCY]: [
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.8}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.7}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.6}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.5}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.4}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.3}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.2}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.1}),
                    lightenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.1}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.2}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.3}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.4}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.5}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.6}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.7}),
                    darkenHexColor({ hexColor: defaultPalette[colorAssociations[Feeling.URGENCY][Culture.CHINESE]], force: 0.8}),
                ],
            }
        })
    })
})